### PR TITLE
Replace XMLHttpRequest with fetch

### PR DESCRIPTION
**Pull request by verdie-g**

### CODE REVIEW

**Review by mortrevere — APPROVED** [review]
full ES6 transition was on the roadmap but this looks better in term of event flow and `this`

**Review by mortrevere — CHANGES_REQUESTED** [review]
by looking at the PR I don't think it supports multi source aggregation which is the whole point of snips

**Comment by verdie-g** [comment]
I'm not sure to understand. Does the request should be made and each element of the SOURCES array ?

**Comment by mortrevere** [comment]
Yes, the aggregation of snips is based around that subscriber model, where you reference the sources (here, raw.github hotlinks) you want to use for your snip browsing. Future development will add the ability to add/remove sources from the web client.

Check the current master, it includes another snip repo (the first one :octopus:) from @LysandreJik in the SOURCES array

**Review by mortrevere — APPROVED** [review]
nice, clean rewrite

**Pull request merged**
